SSISPayroll/Controllers/BrassCodeConversionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using SSISPayroll.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace SSISPayroll.Controllers
{
    public class BrassCodeConversionController: Controller
    {
        private readonly HSDBContext _context;

        public BrassCodeConversionController(HSDBContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> IndexAsync()
        {
            var brassconversion = _context.SsisRoleBrassConversion;
            return View(await brassconversion.ToListAsync());
            
        }



        public IActionResult Create()
        {           
            return PartialView("_CreatePartial");
        }

        // POST: FinishedSigns/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SsisRoleBrassConversionId,SsisRoleId,Brass,OrgCode")] SsisRoleBrassConversion ssisrolebrassconversion)
        {
            

            if (ModelState.IsValid)
            {
                if (!SsisRoleBrassConversionExists(ssisrolebrassconversion))
                {
                    _context.Add(ssisrolebrassconversion);
                    await _context.SaveChangesAsync();

                    //return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError("", "This record already exist!!");
                }
                
            }


            return PartialView("_CreatePartial", ssisrolebrassconversion);
        }



        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ssisrolebrassconversion = await _context.SsisRoleBrassConversion.SingleOrDefaultAsync(m => m.SsisRoleBrassConversionId == id);
            if (ssisrolebrassconversion == null)
            {
                return NotFound();
            }

            return PartialView("_EditPartial", ssisrolebrassconversion);

        }

        // POST: FinishedSigns/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit( [Bind("SsisRoleBrassConversionId,SsisRoleId,Brass,OrgCode")] SsisRoleBrassConversion ssisrolebrassconversion)
        {
           
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ssisrolebrassconversion);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SsisRoleBrassConversionExists(ssisrolebrassconversion))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            
            return View(ssisrolebrassconversion);
        }




        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var ssisrolebrassconversion = await _context.SsisRoleBrassConversion.SingleOrDefaultAsync(m => m.SsisRoleBrassConversionId == id);
            if (ssisrolebrassconversion == null)
            {
                return NotFound();
            }
            

            return PartialView("_DeletePartial", ssisrolebrassconversion);
        }

        // POST: FinishedSigns/Delete/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(SsisRoleBrassConversion ssisrolebrassconversion)
        {

            var SsisRoleBrassConver = await _context.SsisRoleBrassConversion.FindAsync(ssisrolebrassconversion.SsisRoleBrassConversionId);
           
            

            if (ModelState.IsValid)
            {
                try
                {
                    _context.SsisRoleBrassConversion.Remove(SsisRoleBrassConver);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SsisRoleBrassConversionExists(ssisrolebrassconversion))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                
            }
            return RedirectToAction(nameof(Index));
        }



        public IActionResult Privacy()
        {
            return View();
        }

        [AllowAnonymous]
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        private bool SsisRoleBrassConversionExists(SsisRoleBrassConversion ssisrolebrassconv)
        {
            return _context.SsisRoleBrassConversion.Any(e => 
            e.SsisRoleId==ssisrolebrassconv.SsisRoleId && 
            e.Brass==ssisrolebrassconv.Brass &&
            e.OrgCode==ssisrolebrassconv.OrgCode);
        }
    }
}

SSISPayroll/Views/BrassCodeConversion/Index.cshtml
@model IEnumerable<SSISPayroll.Models.SsisRoleBrassConversion>
@{
    ViewData["Title"] = "Index";
}
<h3>Brass Code Conversion</h3>
<br />
<div class="row">
    <div class="col-md-6">
        <a class="btn btn-dark btn-sm" data-toggle="modal" asp-action="Create" id="btnCreate">New Brass Code Conversion</a>
    </div>
</div>
<br />
<table class="table table-condensed table-striped table-bordered small" id="brassroleconversiontable">
    <thead>
        <tr>
            @*<th>

                    @Html.DisplayNameFor(model => model.SsisRoleBrassConversionId)
                </th>*@
            <th>
                SSIS Role Id
                @*@Html.DisplayNameFor(model => model.SsisRoleId)*@
            </th>
            <th>
                Brass
                @*@Html.DisplayNameFor(model => model.Brass)*@
            </th>
            <th>
                Org Code
                @*@Html.DisplayNameFor(model => model.OrgCode)*@
            </th>
            <th width="15%">

            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                @*<td width="20%">
                        @Html.DisplayFor(modelItem => item.SsisRoleBrassConversionId)
                    </td>*@
                <td width="20%">
                    @Html.DisplayFor(modelItem => item.SsisRoleId)
                </td>
                <td width="20%">
                    @Html.DisplayFor(modelItem => item.Brass)
                </td>
                <td width="20%">
                    @Html.DisplayFor(modelItem => item.OrgCode)
                </td>
                <td width="15%">
                    <a class="btn btn-outline-dark btn-sm editCrud" data-toggle="modal" asp-action="Edit" asp-route-id="@item.SsisRoleBrassConversionId">Edit</a> |
                    <a class="btn btn-outline-danger btn-sm deleteCrud" data-toggle="modal" asp-action="Delete" asp-route-id="@item.SsisRoleBrassConversionId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<!-- Modal -->
<div class="modal fade in" id="crudModal" tabindex="-1" role="dialog" aria-labelledby="createModal" aria-hidden="true">
    <div id="crudContainer">
    </div>
</div>


@section Scripts {

    <!-- For the DataTables grid -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>

    <!-- Page-specific script -->

    <script src="~/js/site.js" asp-append-version="true"></script>

    <script type="text/javascript">
        $(function () {
            var placeholderElement = $('#crudContainer');

            $(document).ready(function () {
                $('#brassroleconversiontable').DataTable({
                    "paging": true // false to disable pagination (or any other option)
                });
                $('.dataTables_length').addClass('bs-select');
            });



            $("#btnCreate").on("click", function () {
                $('#crudContainer').load(this.href, function () {

                    $('#crudModal').modal('show');
                });
                return false;
            });

            $('#brassroleconversiontable').on("click", ".editCrud", function (event) {
                event.preventDefault();
                var url = $(this).attr("href");
                $.get(url, function (data) {
                    $('#crudContainer').html(data);
                    $('#crudModal').modal('show');
                });
            });

            $('#brassroleconversiontable').on("click", ".deleteCrud", function (event) {
                event.preventDefault();
                var url = $(this).attr("href");
                $.get(url, function (data) {
                    $('#crudContainer').html(data);
                    $('#crudModal').modal('show');
                });
            });

        });


    </script>

    
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
   
}

SSISPayroll/Views/BrassCodeConversion/_CreatePartial.cshtml
@model SSISPayroll.Models.SsisRoleBrassConversion
@*<div data-role="page">
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    </div>*@
<div class="modal-dialog">
    <div class="modal-content">
        <div class="row">
            <div class="col-md-12">
                <form id="myform" asp-action="Create">
                    <div class="modal-header">
                        <h5 class="modal-title">New Brass Code Conversion</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    </div>
                    <div class="modal-body">
                        <input name="IsValid" value="@ViewData.ModelState.IsValid.ToString()" />
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="SsisRoleId" class="control-label"></label>
                            <input id="ssisroleid" asp-for="SsisRoleId" class="form-control" />
                            <span asp-validation-for="SsisRoleId" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Brass" class="control-label"></label>
                            <input id="brass" asp-for="Brass" class="form-control" />
                            <span asp-validation-for="Brass" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="OrgCode" class="control-label"></label>
                            <input id="orgcode" asp-for="OrgCode" class="form-control" />
                            <span asp-validation-for="OrgCode" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-outline-dark btn-sm" data-dismiss="modal">Close</button>
                        <input type="submit" id="btnSaveIt" data-save="modal" class="btn btn-dark btn-sm" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    $(document).ready(function () {

        $("#btnSaveIt").on("click", function () {

            event.preventDefault();

            var form = $(this).parents('.modal').find('form');
            var actionUrl = form.attr('action');
            var dataToSend = form.serialize();

            $.post(actionUrl, dataToSend).done(function (data) {
                var newBody = $('.modal-body', data);
                $('#crudContainer').find('.modal-body').replaceWith(newBody);

                var isValid = newBody.find('[name="IsValid"]').val() == 'True';
                if (isValid) {
                    window.location = '@Url.Action("Index", "BrassCodeConversion")'
                    $('#crudModal').modal('hide');
                }

            });

        });



    });
</script>

SSISPayroll/Views/BrassCodeConversion/_DeletePartial.cshtml
@model SSISPayroll.Models.SsisRoleBrassConversion

    <div class="modal-dialog">
        <div class="modal-content">
            <div class="row">
                <div class="col-md-12">
                    <form asp-action="Delete">
                        <div class="modal-header">
                            <h5 class="modal-title">Delete Brass Code Conversion</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        </div>
                        <div class="modal-body">
                            <h6>Are you sure you want to delete this record?</h6>
                            <hr />
                            <div>
                                <dl class="row">
                                    <dt class="col-sm-4">
                                        @Html.DisplayNameFor(model => model.SsisRoleId)
                                    </dt>
                                    <dd class="col-sm-8">
                                        @Html.DisplayFor(model => model.SsisRoleId)
                                        <input type="hidden" asp-for="SsisRoleId" />
                                    </dd>
                                    <dt class="col-sm-4">
                                        @Html.DisplayNameFor(model => model.Brass)
                                    </dt>
                                    <dd class="col-sm-8">
                                        @Html.DisplayFor(model => model.Brass)
                                        <input type="hidden" asp-for="Brass" />
                                    </dd>
                                    <dt class="col-sm-4">
                                        @Html.DisplayNameFor(model => model.OrgCode)
                                    </dt>
                                    <dd class="col-sm-8">
                                        @Html.DisplayFor(model => model.OrgCode)
                                        <input type="hidden" asp-for="OrgCode" />
                                    </dd>
                                </dl>
                            </div>
                        </div>
                        <div class="modal-footer">                            
                            <input type="hidden" asp-for="SsisRoleBrassConversionId" />
                            <input type="submit" value="Yes" class="btn btn-dark btn-sm" />
                            <button type="button" class="btn btn-outline-dark btn-sm" data-dismiss="modal">No</button>                           
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

SSISPayroll/Views/BrassCodeConversion/_EditPartial.cshtml
@model SSISPayroll.Models.SsisRoleBrassConversion

<div class="modal-dialog">
    <div class="modal-content">
        <div class="row">
            <div class="col-md-12">
                <form asp-action="Edit">
                    <div class="modal-header">
                        <h5 class="modal-title">Edit Brass Code Conversion</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    </div>
                    <div class="modal-body">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group" hidden>
                            <label asp-for="SsisRoleBrassConversionId" class="control-label"></label>
                            <input asp-for="SsisRoleBrassConversionId" class="form-control" />
                            <span asp-validation-for="SsisRoleBrassConversionId" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="SsisRoleId" class="control-label"></label>
                            <input asp-for="SsisRoleId" class="form-control" />
                            <span asp-validation-for="SsisRoleId" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Brass" class="control-label"></label>
                            <input asp-for="Brass" class="form-control" />
                            <span asp-validation-for="Brass" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="OrgCode" class="control-label"></label>
                            <input asp-for="OrgCode" class="form-control" />
                            <span asp-validation-for="OrgCode" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-outline-dark btn-sm" data-dismiss="modal">Close</button>
                        <input type="submit" value="Edit" class="btn btn-dark btn-sm" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>